### ISSUE TITLE
Driver License Bar Code

### ISSUE THREAD

**Issue by bkoffler** [ihabunek/pdf417-py#13]
Hi - i am working on a project, part of which involves generating barcodes which would be found on IDs as a means of verification for users. Essentially i am trying to recreate the barcode like this:

https://docs.scandit.com/parser/dlid.html

Is this something that your program can do? I don't see why it couldn't technically but i am just not sure how it would be done. Please let me know whenever you have a chance.

**Comment by ihabunek** [comment]
Not sure if you closed the issue on purpose or not.

The linked page does not mention any specific barcode format, it only mentions the data contained in the barcodes.

You could use pdf417gen to encode this data to an PDF417 barcode, e.g. using the example from the linked page:

```
pdf417gen encode --columns 10 "@\n\x1e\rANSI 636000090002DL00410278ZV03190008DLDAQT64235789\nDCSSAMPLE\nDDEN\nDACMICHAEL\nDDFN\nDADJOHN\nDDGN\nDCUJR\nDCAD\nDCBK\nDCDPH\nDBD06062016\nDBB06061986\nDBA12102024\nDBC1\nDAU068 in\nDAYBRO\nDAG2300 WEST BROAD STREET\nDAIRICHMOND\nDAJVA\nDAK232690000  \nDCF2424244747474786102204\nDCGUSA\nDCK123456789\nDDAF\nDDB06062008\nDDC06062009\nDDD1\rZVZVA01\r"
```

Creates this barcode:

![example](https://user-images.githubusercontent.com/482138/51589235-b638d500-1ee6-11e9-87f0-5acb9229b9a5.png)

**Comment by bkoffler** [comment]
Hi Ivan -

Yea I realized the issue I was having right after i opened the ticket and was able to do what i needed. This is a great piece of software you put together - thank you.

Thanks again for getting back to me so quickly.

**Comment by ihabunek** [comment]
Thanks. No problem. :)

**Comment by SatandavidLuicief** [comment]
@

ANSI 636014090102DL00410277ZC03180024DLDAQD4759942
DCSMOORE
DDEN
DACDAVID
DDFN
DADANDREW
DDGN
DCAC
DCBNONE
DCDNONE
DBD06192023
DBB03141984
DBA03142027
DBC1
DAU074 IN
DAYBLU
DAG209 CAROLOS DR
DAIPACHECO
DAJCA
DAK945530000  
DCF04/04/2022523OD/CCFD/27
DCGUSA
DAW260
DAZBRO
DCK23170D47599420401
DDAF
DDB08292017
DDK1
ZCZCABLU
ZCBBRN
ZCC
ZCD
