### ISSUE TITLE
Float module

### ISSUE THREAD

**Issue by ProdByGR** [ihabunek/pdf417-py#14]
if i do `render_image(data, scale=4.5)`

i get a 

> TypeError: integer argument expected, got float

how can i use float instead of integer in scale?

**Comment by ihabunek** [comment]
Non-integer scale does not makes sense. If you specify scale=4.5 and ratio=3, the dots on the bar chart would have to be 4.5px by 13.5px large, which is not possible because images don't have fractional pixels.
