### ISSUE TITLE
Python3 isn't supported

### ISSUE THREAD

**Issue by kalloc** [ihabunek/pdf417-py#4]
Hi

I found support declaration in setup.py.

But it is impossible to encode something like b'\x01'

**Comment by ihabunek** [comment]
@kalloc So this turned out to be a bit fiddly. Please check out PR #5.
If it works fine for you, I will merge it and deploy the next version.

**Comment by kalloc** [comment]
@ihabunek Yes, it works on my case, thank you

**Comment by ihabunek** [comment]
@kalloc The release is up:
https://pypi.python.org/pypi/pdf417gen 

Thanks for the report. Feedback is always welcome.

**Comment by kalloc** [comment]
thank you!
