### ISSUE TITLE
Wrong encoder for mixed type (with byte)

### ISSUE THREAD

**Issue by kalloc** [ihabunek/pdf417-py#6]
Hi.

I save bytes to pdf417
> hex_buf = '011b0000f829a358e1610100000001000000dfee82de5b9607c5186ce75de352648cfde9a15114305ebe39ed1db4940f3aa3cd89086ea5eb8db01fbe8255b0b0a5fbebca7a123859fc86f2ddfcb1abfd71e5'
> buf = bytes.fromhex(hex_buf)
> print(len(buf))
> # 82
> codes = encode(buf)
> img = render_image(codes)
> img.save('1.jpeg')

produced this image ![230112158_11982600991711161154](https://cloud.githubusercontent.com/assets/177687/22937158/d6437eda-f2e8-11e6-9a82-77c6f80f9b09.jpg)

When I check image on https://www.dynamsoft.com/Demo/DBR/BarcodeReaderDemo.aspx I got 
`011b0000f829a358e1610100000001005b9607c5186ce77de352648cfde9a15114305ebe39ed1db4940f3aa3cd89086ea5eb8db01fbe8255b0b0a5fbebca7a123859fc86f2ddfcb1abfd71e5`

> new_hex_buf = '011b0000f829a358e1610100000001005b9607c5186ce77de352648cfde9a15114305ebe39ed1db4940f3aa3cd89086ea5eb8db01fbe8255b0b0a5fbebca7a123859fc86f2ddfcb1abfd71e5'
> new_buf = bytes.fromhex(new_hex_buf)
> print(len(new_buf))
> # 76
6 bytes missed :(

**Comment by ihabunek** [comment]
I will look into it, probably over the weekend.

**Comment by kalloc** [comment]
Did you have free time?

**Comment by ihabunek** [comment]
Sorry, I have been traveling and had other work. Before fixing, I'd like to find another another decoder to make sure the issue is with my encoding and not with their decoding. The one had time to try out (https://sourceforge.net/projects/pdf417decode/) did not work on my machine for some reason, would not recognize the barcode image format.

I'll try to find time to work on this soon, but can't promise you anything.

**Comment by ihabunek** [comment]
BTW, this reader gives a different decoding result, also different from input :/
https://online-barcode-reader.inliteresearch.com/

**Comment by ihabunek** [comment]
Not really. Working. See the issue.



-- Ivan







On Mon, 27 Feb 2017, at 14:57, kalloc wrote:

> Did you have free time?



> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
> 




Links:

  1. https://github.com/ihabunek/pdf417-py/issues/6#issuecomment-282726574

**Comment by kalloc** [comment]
I did use [bcgen](http://www.bcgen.com/pdf417-barcode-creator.html) for generate  [image](http://www.bcgen.com/demo/IDAutomationStreamingPDF417.aspx?ECL=4&D=%01%1B%00%00%F8%29%A3X%E1a%01%00%00%00%01%00%00%00%DF%EE%82%DE%5B%96%07%C5%18l%E7%5D%E3Rd%8C%FD%E9%A1Q%140%5E%BE9%ED%1D%B4%94%0F%3A%A3%CD%89%08n%A5%EB%8D%B0%1F%BE%82U%B0%B0%A5%FB%EB%CAz%128Y%FC%86%F2%DD%FC%B1%AB%FDq%E5&MODE=Binary&PT=F&X=0.15&O=0&LM=0.2&ROWS=0&COL=4&TRN=0&XYR=3&MAE=F&MAF=0&MAS=0&MAL=F) with test example from this ticket (82 bytes).
Then I uploaded this image into [dynamsoft](https://www.dynamsoft.com/Demo/DBR/BarcodeReaderDemo.aspx)  decoder and got only 77 bytes instead of 82

**Comment by kalloc** [comment]
1) we need working generator
2) as I understand, dynamsoft decoder works well

**Comment by kalloc** [comment]
This ![82byte_pdf417_example](https://cloud.githubusercontent.com/assets/177687/23369609/04bf6c6c-fd23-11e6-8d3e-3d08f2d62a5f.png) file was successfully decoded in [dynamsoft.com](https://www.dynamsoft.com/Demo/DBR/BarcodeReaderDemo.aspx)

**Comment by kalloc** [comment]
I found valid coder.
```
        import zint
        from ctypes import create_string_buffer, memmove
        import PIL
        import io

        input = zint.instr(data)
        symbol = zint.ZBarcode_Create()
        symbol.contents.symbology = zint.BARCODE_PDF417
        symbol.contents.option_1 = 4
        symbol.contents.option_2 = 4
        # symbol.contents.border_width = 4

        input = zint.instr(ticket_data)
        zint.ZBarcode_Encode_and_Buffer(symbol, input, len(input) - 1, 0)
        BITMAP_SIZE = symbol.contents.bitmap_height * symbol.contents.bitmap_width * 3
        buf = create_string_buffer(BITMAP_SIZE)
        memmove(buf, symbol.contents.bitmap, BITMAP_SIZE)
        im = PIL.Image.frombytes('RGB', (symbol.contents.bitmap_width, symbol.contents.bitmap_height), bytes(buf))
        b = io.BytesIO()
        im.save(b, format='PNG')
        image = b.getvalue()
        zint.ZBarcode_Delete(symbol)
        return image
```
