### ISSUE TITLE
ValueError: Data too long. Generated bar code contains 1254 code words. Maximum is 928. Try decreasing security level.

### ISSUE THREAD

**Issue by unclesamer** [ihabunek/pdf417-py#9]
So I've been trying to use the library to generate a pdf417, and I have specific requirements to use security level 6 and 16 columns. I have received some examples showing that this is possible however the library always throws an error.

What do you think ?
Here's a snippet: 

```
from pdf417gen import encode, render_image, render_svg

barcode_data = "DEBBOR 189686 20012017 0000000050 2V0093286129 13 008    2V0093286130 69 002    2V0093286131 75 018    2V0093286132 75 008    2V0093286133 44 800    2V0093286134 60 230    2V0093286135 95 710    2V0093286136 55 260    2V0093286137 31 450    2V0093286138 54 730    2V0093286139 67 390    2V0093286140 21 000    2V0093286141 69 007    2V0093286142 59 390    2V0093286143 42 100    2V0093286144 59 570    2V0093286145 75 011    2V0093286146 84 480    2V0093286147 75 008    2V0093286148 91 170    2V0093286149 35 000    2V0093286150 06 810    2V0093286151 95 200    2V0093286152 42 820    2V0093286153 75 016    2V0093286154 06 620    2V0093286155 23 150    2V0093286156 09 700    2V0093286157 92 500    2V0093286158 25 000    2V0093286159 86 000    2V0093286160 75 014    2V0093286161 78 150    2V0093286162 28 100    2V0093286163 20 620    2V0093286164 75 012    2V0093286165 62 118    2V0093286166 22 160    2V0093286167 13 009    2V0093286168 44 000    2V0093286169 75 019    2V0093286170 06 000    2V0093286171 54 000    2V0093286172 31 130    2V0093286173 71 250    2V0093286174 75 005    2V0093286175 64 600    2V0093286176 60 130    2V0093286177 37 000    2V0093286178 34 450    2V0093286179 93 000    2V0093286180 75 010    2V0093286181 38 220    2V0093286182 78 000    2V0093286183 06 100    2V0093286184 59 215    2V0093286185 92 600    2V0093286186 25 130    FINBOR"
path = "/var/barcode.jpg"

codes = encode(barcode_data, columns=16, security_level=6)
image = render_image(codes)
image.save(path)
```

**Comment by ihabunek** [comment]
Hey, sorry for the slow reaction time.

I doublechecked my code and indeed found an error which limited the barcode size to lower than necessary (see commit 4268680), but it is still not enough for @unclesamer 's sample snippet.

To quote the spec:

> The data region of a PDF417 symbol is the central area of codeword columns between the left row indicator column and the right row indicator column. The first (upper left) codeword of the data region is the symbol length descriptor. Its value indicates the total number of codewords in the data region, including the symbol length descriptor itself, but excluding the error correction codewords. The remaining codewords in the data region (including the data codewords, pad codewords, and error correction codewords. in that order) are arranged with the most significant codeword adjacent to the symbol length descriptor, and are read from left to right, top row to bottom. The total number of codewords in the data region of a single PDF417 symbol cannot exceed 928.

It might be possible to squeeze more data in by doing some optimizations which have not yet been implemented. For example, the code in #12 brings down the number of code words from 1248 to 1072 (still not enough).

I'll keep working on this, but the pace might be slow.

**Comment by ihabunek** [comment]
@unclesamer @thehappydinoa I just pushed version 0.7.0 which greatly improves the amount of data which can be encoded in a bar code. Check it out. The snippet provided by @unclesamer now generates a bar code successfully.
